name = "Ruins of the Ancients MULTIPLAYER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a1494d78723bc56a0cd6821a16005f83e91cfa546326c6ca61da4cfb7bcc286"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
