name = "Ruins of the Ancients MULTIPLAYER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8632318b49d3167ba40e03d8c72b1a83fd1ae211da1af1133dc6c93dbf9e339"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
