name = "Ruins of the Ancients MULTIPLAYER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d83f681c323f2a55fa51a00efeb1d7c9965ba9ed4013fb3eadd08c7a2a34fc71"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
