name = "Ruins of the Ancients MULTIPLAYER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50abdc94c81be5df19dd4e3f3fab1ead92868a7139e39fd18cb82d739ab6ae25"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
