name = "Ruins of the Ancients MULTIPLAYER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b239c47dada152680e5300504d1e06bd948858ecc71fd7e9b2907dbbeb16d5ea"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
