name = "Ruins of the Ancients MULTIPLAYER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89e49c35e4beb80c4c4509fea2c55c893c55ca08e8e636aecdc0d66f10ed0a37"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
