name = "Ruins of the Ancients MULTIPLAYER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a9bc612ab8aba4ef35870a81d933b54fa725d07e3471b7353ac40df4609fc7f"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
