name = "Ruins of the Ancients MULTIPLAYER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91ecad0553f692abbd44b6c9cb1ca1e3d5dc0789287ac2e761875955c39d411d"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
